name = "https-github"
main = "src/talaba-edge-worker.ts"
compatibility_date = "2026-06-21"

assets = { directory = "./dist", binding = "ASSETS", not_found_handling = "single-page-application" }

routes = [
  { pattern = "talaba.kaniq.org", custom_domain = true, zone_name = "kaniq.org" }
]
