name = "https-github"
main = "worker-static.js"
compatibility_date = "2025-06-01"

[assets]
directory = "./dist"
binding = "ASSETS"
not_found_handling = "single-page-application"
[[routes]]
pattern = "talaba.kaniq.org"
custom_domain = true

