-- Jamiaati real D1 content seed

-- Generated at 2026-06-14T11:18:10.105Z

-- Targets: opportunity_sources, opportunity_candidates, highlight_items



-- No explicit transaction: Cloudflare D1 remote file execution rejects BEGIN/COMMIT here.

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'un-iraq-jobs-official',
  'United Nations Iraq Jobs',
  'https://iraq.un.org/en/jobs',
  'job_board',
  'jobs',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'jobs',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'undp-iraq-jobs',
  'UNDP Iraq Jobs',
  'https://jobs.undp.org',
  'job_board',
  'jobs',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'jobs',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'reliefweb-iraq-jobs',
  'ReliefWeb Iraq Jobs',
  'https://reliefweb.int/jobs?advanced-search=%28C104%29',
  'job_board',
  'jobs',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'jobs',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'ncci-iraq-jobs',
  'NCCI Iraq Jobs',
  'https://ncciraqjobs.com',
  'job_board',
  'jobs',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'jobs',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'iom-iraq-careers',
  'IOM Iraq Careers',
  'https://iraq.iom.int/careers',
  'job_board',
  'jobs',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'jobs',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'zain-iraq-careers',
  'Zain Iraq Careers',
  'https://iq.zain.com/en/careers',
  'job_board',
  'jobs',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'jobs',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'asiacell-careers-official',
  'Asiacell Careers',
  'https://www.asiacell.com/en/about-us/careers',
  'job_board',
  'jobs',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'jobs',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'korek-careers',
  'Korek Telecom Careers',
  'https://www.korektel.com',
  'job_board',
  'jobs',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'jobs',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'bayt-iraq-jobs',
  'Bayt Iraq Jobs',
  'https://www.bayt.com/en/iraq/jobs/',
  'job_board',
  'jobs',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'jobs',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'linkedin-iraq-jobs',
  'LinkedIn Iraq Jobs',
  'https://www.linkedin.com/jobs/search/?location=Iraq',
  'job_board',
  'jobs',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'jobs',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'daad-iraq-scholarship-database',
  'DAAD Iraq Scholarship Database',
  'https://www.daad-iraq.org/en/find-funding/scholarship-database/',
  'scholarship_portal',
  'scholarships',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'scholarships',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'chevening-iraq',
  'Chevening Iraq Scholarships',
  'https://www.chevening.org/scholarships/iraq/',
  'scholarship_portal',
  'scholarships',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'scholarships',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'erasmus-mundus-catalogue',
  'Erasmus Mundus Joint Masters Catalogue',
  'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en',
  'scholarship_portal',
  'scholarships',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'scholarships',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'turkiye-scholarships',
  'TÃ¼rkiye Scholarships',
  'https://www.turkiyeburslari.gov.tr',
  'scholarship_portal',
  'scholarships',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'scholarships',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'mext-japan-iraq',
  'MEXT Japan Scholarships Iraq',
  'https://www.iraq.emb-japan.go.jp',
  'scholarship_portal',
  'scholarships',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'scholarships',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'campus-france-iraq-scholarships',
  'Campus France Iraq Scholarships',
  'https://www.iraq.campusfrance.org',
  'scholarship_portal',
  'scholarships',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'scholarships',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'fulbright-iraq',
  'Fulbright Iraq',
  'https://iq.usembassy.gov/education-culture/exchange-programs/',
  'scholarship_portal',
  'scholarships',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'scholarships',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'study-in-canada-scholarships',
  'Study in Canada Scholarships',
  'https://www.educanada.ca/scholarships-bourses/index.aspx',
  'scholarship_portal',
  'scholarships',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'scholarships',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'opportunity-desk',
  'Opportunity Desk',
  'https://opportunitydesk.org',
  'scholarship_portal',
  'scholarships',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'scholarships',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'for9a-scholarships',
  'For9a Scholarships',
  'https://www.for9a.com',
  'scholarship_portal',
  'scholarships',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'scholarships',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'university-of-baghdad-news',
  'University of Baghdad News',
  'https://uobaghdad.edu.iq',
  'university',
  'announcements',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'announcements',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'mustansiriyah-university-news',
  'Al-Mustansiriya University News',
  'https://uomustansiriyah.edu.iq',
  'university',
  'announcements',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'announcements',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'university-of-sulaimani-news',
  'University of Sulaimani News',
  'https://univsul.edu.iq',
  'university',
  'announcements',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'announcements',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'salahaddin-university-news',
  'Salahaddin University News',
  'https://su.edu.krd',
  'university',
  'announcements',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'announcements',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'university-of-mosul-news',
  'University of Mosul News',
  'https://uomosul.edu.iq',
  'university',
  'announcements',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'announcements',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'university-of-basrah-news',
  'University of Basrah News',
  'https://uobasrah.edu.iq',
  'university',
  'announcements',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'announcements',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'koya-university-news',
  'Koya University News',
  'https://koyauniversity.org',
  'university',
  'announcements',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'announcements',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'auis-news',
  'American University of Iraq Sulaimani News',
  'https://auis.edu.krd',
  'university',
  'announcements',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'announcements',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'the-station-iraq-events',
  'The Station Iraq Events',
  'https://the-station.iq',
  'website',
  'events',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'events',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'five-one-labs-events',
  'Five One Labs Events and Programs',
  'https://fiveonelabs.org',
  'website',
  'events',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'events',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_sources (
  id,
  name,
  url,
  source_type,
  category_scope,
  country_scope,
  governorate_scope,
  language,
  is_active,
  crawl_frequency_hours,
  notes,
  type,
  active,
  enabled,
  created_at,
  updated_at
)
VALUES (
  'kapita-iraq-events',
  'KAPITA Iraq Events',
  'https://kapita.iq',
  'website',
  'events',
  'Iraq',
  'all',
  'mixed',
  1,
  24,
  'Seeded from Jamiaati content population pack. Pending review workflow only; no auto publish.',
  'events',
  1,
  1,
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO opportunity_candidates (
  id,
  source_id,
  title,
  organization,
  category,
  description,
  summary,
  eligibility,
  deadline,
  published_date,
  apply_url,
  source_url,
  image_url,
  country,
  governorate,
  city,
  language,
  salary_or_funding,
  confidence_score,
  duplicate_key,
  status,
  created_at,
  updated_at,
  titleEN,
  titleAR,
  titleKU,
  university,
  governorateId,
  source_website,
  original_source_url,
  application_link,
  sourceUrl,
  contentEN,
  contentAR,
  contentKU,
  raw_extracted_text
)
VALUES (
  'seed-scholarship-daad-iraq',
  'daad-iraq-scholarship-database',
  'DAAD Scholarship Database for Iraqi Students',
  'DAAD Iraq',
  'scholarship',
  'A trusted scholarship database for Iraqi students, graduates, researchers, and academics looking for study and research funding in Germany. Check the official DAAD page for the exact current deadline and requirements.',
  'A trusted scholarship database for Iraqi students, graduates, researchers, and academics looking for study and research funding in Germany. Check the official DAAD page for the exact current deadline and requirements.',
  'Iraqi students, graduates, researchers, and academics',
  'Check official website',
  '2026-06-14T11:18:10.105Z',
  'https://www.daad-iraq.org/en/find-funding/scholarship-database/',
  'https://www.daad-iraq.org/en/find-funding/scholarship-database/',
  'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=900',
  'Germany',
  'all',
  'Germany',
  'mixed',
  'Study abroad',
  90,
  'seed-opportunity-seed-scholarship-daad-iraq',
  'pending_review',
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z',
  'DAAD Scholarship Database for Iraqi Students',
  'Ù‚Ø§Ø¹Ø¯Ø© Ø¨ÙŠØ§Ù†Ø§Øª Ù…Ù†Ø­ DAAD Ù„Ù„Ø·Ù„Ø§Ø¨ Ø§Ù„Ø¹Ø±Ø§Ù‚ÙŠÙŠÙ†',
  'Ø¨Ù†Ú©Û•ÛŒ Ø²Ø§Ù†ÛŒØ§Ø±ÛŒ Ø¨ÙˆØ±Ø³Û•Ú©Ø§Ù†ÛŒ DAAD Ø¨Û† Ù‚ÙˆØªØ§Ø¨ÛŒØ§Ù†ÛŒ Ø¹ÛŽØ±Ø§Ù‚',
  'all',
  'all',
  'https://www.daad-iraq.org/en/find-funding/scholarship-database/',
  'https://www.daad-iraq.org/en/find-funding/scholarship-database/',
  'https://www.daad-iraq.org/en/find-funding/scholarship-database/',
  'https://www.daad-iraq.org/en/find-funding/scholarship-database/',
  'A trusted scholarship database for Iraqi students, graduates, researchers, and academics looking for study and research funding in Germany. Check the official DAAD page for the exact current deadline and requirements.',
  'Ù‚Ø§Ø¹Ø¯Ø© Ù…ÙˆØ«ÙˆÙ‚Ø© Ù„Ù„Ù…Ù†Ø­ Ø§Ù„Ø¯Ø±Ø§Ø³ÙŠØ© Ù„Ù„Ø·Ù„Ø§Ø¨ ÙˆØ§Ù„Ø®Ø±ÙŠØ¬ÙŠÙ† ÙˆØ§Ù„Ø¨Ø§Ø­Ø«ÙŠÙ† ÙˆØ§Ù„Ø£ÙƒØ§Ø¯ÙŠÙ…ÙŠÙŠÙ† Ø§Ù„Ø¹Ø±Ø§Ù‚ÙŠÙŠÙ† Ø§Ù„Ø±Ø§ØºØ¨ÙŠÙ† Ø¨Ø§Ù„Ø¯Ø±Ø§Ø³Ø© Ø£Ùˆ Ø§Ù„Ø¨Ø­Ø« ÙÙŠ Ø£Ù„Ù…Ø§Ù†ÙŠØ§. ÙŠØ±Ø¬Ù‰ Ù…Ø±Ø§Ø¬Ø¹Ø© ØµÙØ­Ø© DAAD Ø§Ù„Ø±Ø³Ù…ÙŠØ© Ù„Ù…Ø¹Ø±ÙØ© Ø¢Ø®Ø± Ù…ÙˆØ¹Ø¯ ÙˆØ´Ø±ÙˆØ· Ø§Ù„ØªÙ‚Ø¯ÙŠÙ… Ø§Ù„Ø­Ø§Ù„ÙŠØ©.',
  'Ø¨Ù†Ú©Û•ÛŒÛ•Ú©ÛŒ Ø¨Ø§ÙˆÛ•Ú•Ù¾ÛŽÚ©Ø±Ø§Ùˆ Ø¨Û† Ø¨ÙˆØ±Ø³Û•Ú©Ø§Ù†ÛŒ Ù‚ÙˆØªØ§Ø¨ÛŒØ§Ù†ØŒ Ø¯Û•Ø±Ú†ÙˆÙˆØ§Ù†ØŒ ØªÙˆÛŽÚ˜Û•Ø±Ø§Ù† Ùˆ Ø¦Û•Ú©Ø§Ø¯ÛŒÙ…ÛŒÛŒÛ• Ø¹ÛŽØ±Ø§Ù‚ÛŒÛŒÛ•Ú©Ø§Ù† Ø¨Û† Ø®ÙˆÛŽÙ†Ø¯Ù† Ùˆ ØªÙˆÛŽÚ˜ÛŒÙ†Û•ÙˆÛ• Ù„Û• Ø¦Û•ÚµÙ…Ø§Ù†ÛŒØ§. ØªÚ©Ø§ÛŒÛ• Ù¾Û•Ú•Û•ÛŒ ÙÛ•Ø±Ù…ÛŒ DAAD Ø¨Ø¨ÛŒÙ†Û• Ø¨Û† Ø¯ÙˆØ§ ÙˆØ§Ø¯Û• Ùˆ Ù…Û•Ø±Ø¬Û•Ú©Ø§Ù†.',
  'A trusted scholarship database for Iraqi students, graduates, researchers, and academics looking for study and research funding in Germany. Check the official DAAD page for the exact current deadline and requirements.'
);

INSERT OR IGNORE INTO opportunity_candidates (
  id,
  source_id,
  title,
  organization,
  category,
  description,
  summary,
  eligibility,
  deadline,
  published_date,
  apply_url,
  source_url,
  image_url,
  country,
  governorate,
  city,
  language,
  salary_or_funding,
  confidence_score,
  duplicate_key,
  status,
  created_at,
  updated_at,
  titleEN,
  titleAR,
  titleKU,
  university,
  governorateId,
  source_website,
  original_source_url,
  application_link,
  sourceUrl,
  contentEN,
  contentAR,
  contentKU,
  raw_extracted_text
)
VALUES (
  'seed-scholarship-chevening-iraq',
  'chevening-iraq',
  'Chevening Scholarships for Iraq',
  'Chevening',
  'scholarship',
  'A major UK scholarship route for future leaders from Iraq to study a one-year master''s degree. Applicants should always check the official Chevening Iraq page for the current cycle dates and eligibility details.',
  'A major UK scholarship route for future leaders from Iraq to study a one-year master''s degree. Applicants should always check the official Chevening Iraq page for the current cycle dates and eligibility details.',
  'Eligible Iraqi applicants for master''s study',
  'Check official website',
  '2026-06-14T11:18:10.105Z',
  'https://www.chevening.org/scholarships/iraq/',
  'https://www.chevening.org/scholarships/iraq/',
  'https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&q=80&w=900',
  'United Kingdom',
  'all',
  'United Kingdom',
  'mixed',
  'Study abroad',
  90,
  'seed-opportunity-seed-scholarship-chevening-iraq',
  'pending_review',
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z',
  'Chevening Scholarships for Iraq',
  'Ù…Ù†Ø­ ØªØ´ÙŠÙÙ†ÙŠÙ†Øº Ù„Ù„Ø¹Ø±Ø§Ù‚',
  'Ø¨ÙˆØ±Ø³ÛŒ Chevening Ø¨Û† Ø¹ÛŽØ±Ø§Ù‚',
  'all',
  'all',
  'https://www.chevening.org/scholarships/iraq/',
  'https://www.chevening.org/scholarships/iraq/',
  'https://www.chevening.org/scholarships/iraq/',
  'https://www.chevening.org/scholarships/iraq/',
  'A major UK scholarship route for future leaders from Iraq to study a one-year master''s degree. Applicants should always check the official Chevening Iraq page for the current cycle dates and eligibility details.',
  'Ù…Ø³Ø§Ø± Ù…Ù‡Ù… Ù„Ù„Ù…Ù†Ø­ Ø§Ù„Ø¨Ø±ÙŠØ·Ø§Ù†ÙŠØ© Ù„Ù‚Ø§Ø¯Ø© Ø§Ù„Ù…Ø³ØªÙ‚Ø¨Ù„ Ù…Ù† Ø§Ù„Ø¹Ø±Ø§Ù‚ Ù„Ø¯Ø±Ø§Ø³Ø© Ø§Ù„Ù…Ø§Ø¬Ø³ØªÙŠØ± Ù„Ù…Ø¯Ø© Ø³Ù†Ø© ÙˆØ§Ø­Ø¯Ø©. ÙŠØ¬Ø¨ Ø¯Ø§Ø¦Ù…Ø§Ù‹ Ù…Ø±Ø§Ø¬Ø¹Ø© ØµÙØ­Ø© ØªØ´ÙŠÙÙ†ÙŠÙ†Øº Ø§Ù„Ø±Ø³Ù…ÙŠØ© Ù„Ù„Ø¹Ø±Ø§Ù‚ Ù„Ù…Ø¹Ø±ÙØ© Ù…ÙˆØ§Ø¹ÙŠØ¯ Ø§Ù„Ø¯ÙˆØ±Ø© Ø§Ù„Ø­Ø§Ù„ÙŠØ© ÙˆØ´Ø±ÙˆØ· Ø§Ù„Ø£Ù‡Ù„ÙŠØ©.',
  'Ú•ÛŽÚ¯Ø§ÛŒÛ•Ú©ÛŒ Ú¯Ø±Ù†Ú¯ÛŒ Ø¨ÙˆØ±Ø³ÛŒ Ø¨Û•Ø±ÛŒØªØ§Ù†ÛŒØ§Ø³Øª Ø¨Û† Ú•Ø§Ø¨Û•Ø±Ø§Ù†ÛŒ Ø¯Ø§Ù‡Ø§ØªÙˆÙˆÛŒ Ø¹ÛŽØ±Ø§Ù‚ Ø¨Û† Ø®ÙˆÛŽÙ†Ø¯Ù†ÛŒ Ù…Ø§Ø³ØªÛ•Ø± Ø¨Û† Ù…Ø§ÙˆÛ•ÛŒ Ø³Ø§ÚµÛŽÚ©. Ù‡Û•Ù…ÛŒØ´Û• Ù¾Û•Ú•Û•ÛŒ ÙÛ•Ø±Ù…ÛŒ Chevening Iraq Ø¨Ù¾Ø´Ú©Ù†Û• Ø¨Û† ÙˆØ§Ø¯Û• Ùˆ Ù…Û•Ø±Ø¬Û• Ù†ÙˆÛŽÛŒÛ•Ú©Ø§Ù†.',
  'A major UK scholarship route for future leaders from Iraq to study a one-year master''s degree. Applicants should always check the official Chevening Iraq page for the current cycle dates and eligibility details.'
);

INSERT OR IGNORE INTO opportunity_candidates (
  id,
  source_id,
  title,
  organization,
  category,
  description,
  summary,
  eligibility,
  deadline,
  published_date,
  apply_url,
  source_url,
  image_url,
  country,
  governorate,
  city,
  language,
  salary_or_funding,
  confidence_score,
  duplicate_key,
  status,
  created_at,
  updated_at,
  titleEN,
  titleAR,
  titleKU,
  university,
  governorateId,
  source_website,
  original_source_url,
  application_link,
  sourceUrl,
  contentEN,
  contentAR,
  contentKU,
  raw_extracted_text
)
VALUES (
  'seed-scholarship-erasmus-mundus',
  'erasmus-mundus-catalogue',
  'Erasmus Mundus Joint Masters Scholarships',
  'European Union',
  'scholarship',
  'A popular European scholarship path for international students, including Iraqi applicants, through selected joint master''s programs. Students should browse the official catalogue and check each program''s deadline.',
  'A popular European scholarship path for international students, including Iraqi applicants, through selected joint master''s programs. Students should browse the official catalogue and check each program''s deadline.',
  'International students applying to eligible joint master''s programs',
  'Depends on selected program',
  '2026-06-14T11:18:10.105Z',
  'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en',
  'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en',
  'https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?auto=format&fit=crop&q=80&w=900',
  'Europe',
  'all',
  'Europe',
  'mixed',
  'Study abroad',
  90,
  'seed-opportunity-seed-scholarship-erasmus-mundus',
  'pending_review',
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z',
  'Erasmus Mundus Joint Masters Scholarships',
  'Ù…Ù†Ø­ Ø¥ÙŠØ±Ø§Ø³Ù…ÙˆØ³ Ù…ÙˆÙ†Ø¯ÙˆØ³ Ù„Ù„Ù…Ø§Ø¬Ø³ØªÙŠØ± Ø§Ù„Ù…Ø´ØªØ±Ùƒ',
  'Ø¨ÙˆØ±Ø³ÛŒ Erasmus Mundus Ø¨Û† Ù…Ø§Ø³ØªÛ•Ø±ÛŒ Ù‡Ø§ÙˆØ¨Û•Ø´',
  'all',
  'all',
  'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en',
  'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en',
  'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en',
  'https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en',
  'A popular European scholarship path for international students, including Iraqi applicants, through selected joint master''s programs. Students should browse the official catalogue and check each program''s deadline.',
  'Ù…Ø³Ø§Ø± Ø£ÙˆØ±ÙˆØ¨ÙŠ Ù…Ø´Ù‡ÙˆØ± Ù„Ù„Ù…Ù†Ø­ Ù„Ù„Ø·Ù„Ø§Ø¨ Ø§Ù„Ø¯ÙˆÙ„ÙŠÙŠÙ†ØŒ ÙˆÙ…Ù† Ø¶Ù…Ù†Ù‡Ù… Ø§Ù„Ù…ØªÙ‚Ø¯Ù…ÙˆÙ† Ù…Ù† Ø§Ù„Ø¹Ø±Ø§Ù‚ØŒ Ø¹Ø¨Ø± Ø¨Ø±Ø§Ù…Ø¬ Ù…Ø§Ø¬Ø³ØªÙŠØ± Ù…Ø´ØªØ±ÙƒØ© Ù…Ø®ØªØ§Ø±Ø©. ÙŠØ¬Ø¨ ØªØµÙØ­ Ø§Ù„ÙÙ‡Ø±Ø³ Ø§Ù„Ø±Ø³Ù…ÙŠ ÙˆÙ…Ø±Ø§Ø¬Ø¹Ø© Ù…ÙˆØ¹Ø¯ ÙƒÙ„ Ø¨Ø±Ù†Ø§Ù…Ø¬.',
  'Ú•ÛŽÚ¯Ø§ÛŒÛ•Ú©ÛŒ Ù†Ø§Ø³Ø±Ø§ÙˆÛŒ Ø¦Û•ÙˆØ±ÙˆÙˆÙ¾ÛŒÛŒÛ• Ø¨Û† Ø®ÙˆÛŽÙ†Ø¯Ú©Ø§Ø±Ø§Ù†ÛŒ Ù†ÛŽÙˆØ¯Û•ÙˆÚµÛ•ØªÛŒØŒ Ø¨Û• Ù‚ÙˆØªØ§Ø¨ÛŒØ§Ù†ÛŒ Ø¹ÛŽØ±Ø§Ù‚ÛŒØ´Û•ÙˆÛ•ØŒ Ù„Û• Ú•ÛŽÚ¯Û•ÛŒ Ø¨Û•Ø±Ù†Ø§Ù…Û•Ú©Ø§Ù†ÛŒ Ù…Ø§Ø³ØªÛ•Ø±ÛŒ Ù‡Ø§ÙˆØ¨Û•Ø´. Ù‚ÙˆØªØ§Ø¨ÛŒ Ø¯Û•Ø¨ÛŽØª Ú©Ø§ØªÛ•Ù„Û†Ú¯ÛŒ ÙÛ•Ø±Ù…ÛŒ Ø¨Ø¨ÛŒÙ†ÛŽØª Ùˆ Ø¯ÙˆØ§ ÙˆØ§Ø¯Û•ÛŒ Ù‡Û•Ø± Ø¨Û•Ø±Ù†Ø§Ù…Û•ÛŒÛ•Ú© Ø¨Ù¾Ø´Ú©Ù†ÛŽØª.',
  'A popular European scholarship path for international students, including Iraqi applicants, through selected joint master''s programs. Students should browse the official catalogue and check each program''s deadline.'
);

INSERT OR IGNORE INTO opportunity_candidates (
  id,
  source_id,
  title,
  organization,
  category,
  description,
  summary,
  eligibility,
  deadline,
  published_date,
  apply_url,
  source_url,
  image_url,
  country,
  governorate,
  city,
  language,
  salary_or_funding,
  confidence_score,
  duplicate_key,
  status,
  created_at,
  updated_at,
  titleEN,
  titleAR,
  titleKU,
  university,
  governorateId,
  source_website,
  original_source_url,
  application_link,
  sourceUrl,
  contentEN,
  contentAR,
  contentKU,
  raw_extracted_text
)
VALUES (
  'seed-scholarship-turkiye',
  NULL,
  'TÃ¼rkiye Scholarships',
  'TÃ¼rkiye Scholarships',
  'scholarship',
  'Government-funded scholarships for international students at multiple study levels. Iraqi students should check the official portal for the current application cycle, programs, and eligibility.',
  'Government-funded scholarships for international students at multiple study levels. Iraqi students should check the official portal for the current application cycle, programs, and eligibility.',
  'International students, including Iraqi applicants',
  'Check official website',
  '2026-06-14T11:18:10.105Z',
  'https://www.turkiyeburslari.gov.tr',
  'https://www.turkiyeburslari.gov.tr',
  'https://images.unsplash.com/photo-1541432901042-2d8bd64b4a9b?auto=format&fit=crop&q=80&w=900',
  'Turkey',
  'all',
  'Turkey',
  'mixed',
  'Study abroad',
  90,
  'seed-opportunity-seed-scholarship-turkiye',
  'pending_review',
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z',
  'TÃ¼rkiye Scholarships',
  'Ù…Ù†Ø­ ØªØ±ÙƒÙŠØ§',
  'Ø¨ÙˆØ±Ø³ÛŒ ØªÙˆØ±Ú©ÛŒØ§',
  'all',
  'all',
  'https://www.turkiyeburslari.gov.tr',
  'https://www.turkiyeburslari.gov.tr',
  'https://www.turkiyeburslari.gov.tr',
  'https://www.turkiyeburslari.gov.tr',
  'Government-funded scholarships for international students at multiple study levels. Iraqi students should check the official portal for the current application cycle, programs, and eligibility.',
  'Ù…Ù†Ø­ Ù…Ù…ÙˆÙ„Ø© Ù…Ù† Ø§Ù„Ø­ÙƒÙˆÙ…Ø© Ø§Ù„ØªØ±ÙƒÙŠØ© Ù„Ù„Ø·Ù„Ø§Ø¨ Ø§Ù„Ø¯ÙˆÙ„ÙŠÙŠÙ† ÙÙŠ Ø¹Ø¯Ø© Ù…Ø³ØªÙˆÙŠØ§Øª Ø¯Ø±Ø§Ø³ÙŠØ©. Ø¹Ù„Ù‰ Ø§Ù„Ø·Ù„Ø§Ø¨ Ø§Ù„Ø¹Ø±Ø§Ù‚ÙŠÙŠÙ† Ù…Ø±Ø§Ø¬Ø¹Ø© Ø§Ù„Ø¨ÙˆØ§Ø¨Ø© Ø§Ù„Ø±Ø³Ù…ÙŠØ© Ù„Ù…Ø¹Ø±ÙØ© Ø¯ÙˆØ±Ø© Ø§Ù„ØªÙ‚Ø¯ÙŠÙ… Ø§Ù„Ø­Ø§Ù„ÙŠØ© ÙˆØ§Ù„Ø¨Ø±Ø§Ù…Ø¬ ÙˆØ§Ù„Ø´Ø±ÙˆØ·.',
  'Ø¨ÙˆØ±Ø³ÛŒÛŒÛ•Ú©ÛŒ Ø­Ú©ÙˆÙ…ÛŒ ØªÙˆØ±Ú©ÛŒØ§ÛŒÛ• Ø¨Û† Ø®ÙˆÛŽÙ†Ø¯Ú©Ø§Ø±Ø§Ù†ÛŒ Ù†ÛŽÙˆØ¯Û•ÙˆÚµÛ•ØªÛŒ Ù„Û• Ú†Û•Ù†Ø¯ Ø¦Ø§Ø³ØªÛŽÚ©ÛŒ Ø®ÙˆÛŽÙ†Ø¯Ù†. Ù‚ÙˆØªØ§Ø¨ÛŒØ§Ù†ÛŒ Ø¹ÛŽØ±Ø§Ù‚ Ù¾ÛŽÙˆÛŒØ³ØªÛ• Ù¾Û†Ø±ØªØ§ÚµÛŒ ÙÛ•Ø±Ù…ÛŒ Ø¨Ø¨ÛŒÙ†Ù† Ø¨Û† Ø®ÙˆÙ„ÛŒ Ù†ÙˆÛŽÛŒ Ù¾ÛŽØ´Ú©Û•Ø´Ú©Ø±Ø¯Ù† Ùˆ Ø¨Û•Ø±Ù†Ø§Ù…Û• Ùˆ Ù…Û•Ø±Ø¬Û•Ú©Ø§Ù†.',
  'Government-funded scholarships for international students at multiple study levels. Iraqi students should check the official portal for the current application cycle, programs, and eligibility.'
);

INSERT OR IGNORE INTO opportunity_candidates (
  id,
  source_id,
  title,
  organization,
  category,
  description,
  summary,
  eligibility,
  deadline,
  published_date,
  apply_url,
  source_url,
  image_url,
  country,
  governorate,
  city,
  language,
  salary_or_funding,
  confidence_score,
  duplicate_key,
  status,
  created_at,
  updated_at,
  titleEN,
  titleAR,
  titleKU,
  university,
  governorateId,
  source_website,
  original_source_url,
  application_link,
  sourceUrl,
  contentEN,
  contentAR,
  contentKU,
  raw_extracted_text
)
VALUES (
  'seed-scholarship-campus-france-iraq',
  'campus-france-iraq-scholarships',
  'Campus France Iraq Scholarships and Study Routes',
  'Campus France Iraq',
  'scholarship',
  'A useful route for Iraqi students exploring study in France, scholarship information, and admission guidance. Students should check the official Campus France Iraq site for updated calls.',
  'A useful route for Iraqi students exploring study in France, scholarship information, and admission guidance. Students should check the official Campus France Iraq site for updated calls.',
  'Iraqi students interested in France study routes',
  'Check official website',
  '2026-06-14T11:18:10.105Z',
  'https://www.iraq.campusfrance.org',
  'https://www.iraq.campusfrance.org',
  'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?auto=format&fit=crop&q=80&w=900',
  'France',
  'all',
  'France',
  'mixed',
  'Study abroad',
  90,
  'seed-opportunity-seed-scholarship-campus-france-iraq',
  'pending_review',
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z',
  'Campus France Iraq Scholarships and Study Routes',
  'Ù…Ù†Ø­ ÙˆÙ…Ø³Ø§Ø±Ø§Øª Ø§Ù„Ø¯Ø±Ø§Ø³Ø© Ø¹Ø¨Ø± ÙƒØ§Ù…Ø¨ÙˆØ³ ÙØ±Ø§Ù†Ø³ Ø§Ù„Ø¹Ø±Ø§Ù‚',
  'Ø¨ÙˆØ±Ø³ Ùˆ Ú•ÛŽÚ¯Ø§Ú©Ø§Ù†ÛŒ Ø®ÙˆÛŽÙ†Ø¯Ù† Ù„Û• Ú•ÛŽÚ¯Û•ÛŒ Campus France Iraq',
  'all',
  'all',
  'https://www.iraq.campusfrance.org',
  'https://www.iraq.campusfrance.org',
  'https://www.iraq.campusfrance.org',
  'https://www.iraq.campusfrance.org',
  'A useful route for Iraqi students exploring study in France, scholarship information, and admission guidance. Students should check the official Campus France Iraq site for updated calls.',
  'Ù…Ø³Ø§Ø± Ù…ÙÙŠØ¯ Ù„Ù„Ø·Ù„Ø§Ø¨ Ø§Ù„Ø¹Ø±Ø§Ù‚ÙŠÙŠÙ† Ø§Ù„Ø±Ø§ØºØ¨ÙŠÙ† Ø¨Ø§Ù„Ø¯Ø±Ø§Ø³Ø© ÙÙŠ ÙØ±Ù†Ø³Ø§ØŒ ÙˆÙ…Ø¹Ø±ÙØ© Ù…Ø¹Ù„ÙˆÙ…Ø§Øª Ø§Ù„Ù…Ù†Ø­ ÙˆØ§Ù„Ø¥Ø±Ø´Ø§Ø¯Ø§Øª. ÙŠØ¬Ø¨ Ù…Ø±Ø§Ø¬Ø¹Ø© Ù…ÙˆÙ‚Ø¹ ÙƒØ§Ù…Ø¨ÙˆØ³ ÙØ±Ø§Ù†Ø³ Ø§Ù„Ø¹Ø±Ø§Ù‚ Ø§Ù„Ø±Ø³Ù…ÙŠ Ù„Ù…Ø¹Ø±ÙØ© Ø§Ù„Ø¥Ø¹Ù„Ø§Ù†Ø§Øª Ø§Ù„Ø¬Ø¯ÙŠØ¯Ø©.',
  'Ú•ÛŽÚ¯Ø§ÛŒÛ•Ú©ÛŒ Ø¨Ø§Ø´Û• Ø¨Û† Ù‚ÙˆØªØ§Ø¨ÛŒØ§Ù†ÛŒ Ø¹ÛŽØ±Ø§Ù‚ Ú©Û• Ø¯Û•ØªÛ•ÙˆÛŽØª Ù„Û• ÙÛ•Ø±Û•Ù†Ø³Ø§ Ø¨Ø®ÙˆÛŽÙ†Ù† Ùˆ Ø²Ø§Ù†ÛŒØ§Ø±ÛŒÛŒ Ø¨ÙˆØ±Ø³ Ùˆ ÙˆÛ•Ø±Ú¯Ø±ØªÙ† ÙˆÛ•Ø±Ø¨Ú¯Ø±Ù†. ØªÚ©Ø§ÛŒÛ• Ù…Ø§ÚµÙ¾Û•Ú•ÛŒ ÙÛ•Ø±Ù…ÛŒ Campus France Iraq Ø¨Ø¨ÛŒÙ†Ù† Ø¨Û† Ø¨Ø§Ù†Ú¯Û•ÙˆØ§Ø²Û• Ù†ÙˆÛŽÛŒÛ•Ú©Ø§Ù†.',
  'A useful route for Iraqi students exploring study in France, scholarship information, and admission guidance. Students should check the official Campus France Iraq site for updated calls.'
);

INSERT OR IGNORE INTO highlight_items (
  id,
  category,
  title,
  organization,
  governorate,
  city,
  university_id,
  source_name,
  source_url,
  apply_url,
  event_date,
  deadline,
  summary,
  full_description_optional,
  image_url,
  language,
  status,
  duplicate_key,
  confidence_score,
  raw_text,
  created_at,
  updated_at
)
VALUES (
  'seed-social-campus-welcome-english',
  'activity',
  'Welcome to the Campus Life Wall',
  'Jamiaati Campus Life',
  'all',
  'All Iraq',
  'all',
  'Jamiaati Campus Life',
  'internal-demo-campus-life',
  'https://https-github-com-mahdialmuntadhar1-rgb-studenthub-plus.pages.dev',
  '',
  '',
  'This is a starter social post until students begin posting their real campus questions, photos, study groups, and daily university updates. The goal is to keep the app warm without pretending this is official news.',
  '{"titleAR":"Ø£Ù‡Ù„Ø§Ù‹ Ø¨Ùƒ ÙÙŠ Ø³Ø§Ø­Ø© Ø§Ù„Ø­ÙŠØ§Ø© Ø§Ù„Ø¬Ø§Ù…Ø¹ÙŠØ©","titleKU":"Ø¨Û•Ø®ÛŽØ±Ø¨ÛŽÛŒØª Ø¨Û† Ø¯ÛŒÙˆØ§Ø±ÛŒ Ú˜ÛŒØ§Ù†ÛŒ Ø²Ø§Ù†Ú©Û†","contentAR":"Ù‡Ø°Ø§ Ù…Ù†Ø´ÙˆØ± Ø§Ø¬ØªÙ…Ø§Ø¹ÙŠ ØªØ¬Ø±ÙŠØ¨ÙŠ Ø¥Ù„Ù‰ Ø£Ù† ÙŠØ¨Ø¯Ø£ Ø§Ù„Ø·Ù„Ø§Ø¨ Ø¨Ù†Ø´Ø± Ø£Ø³Ø¦Ù„ØªÙ‡Ù… ÙˆØµÙˆØ±Ù‡Ù… ÙˆÙ…Ø¬Ù…ÙˆØ¹Ø§Øª Ø§Ù„Ø¯Ø±Ø§Ø³Ø© ÙˆØªØ­Ø¯ÙŠØ«Ø§ØªÙ‡Ù… Ø§Ù„ÙŠÙˆÙ…ÙŠØ©. Ø§Ù„Ù‡Ø¯Ù Ù‡Ùˆ Ø¬Ø¹Ù„ Ø§Ù„ØªØ·Ø¨ÙŠÙ‚ Ø­ÙŠÙ‘Ø§Ù‹ Ø¯ÙˆÙ† Ø§Ø¯Ø¹Ø§Ø¡ Ø£Ù†Ù‡ Ø®Ø¨Ø± Ø±Ø³Ù…ÙŠ.","contentKU":"Ø¦Û•Ù…Û• Ù¾Û†Ø³ØªÛŽÚ©ÛŒ Ú©Û†Ù…Û•ÚµØ§ÛŒÛ•ØªÛŒ Ø³Û•Ø±Û•ØªØ§ÛŒÛŒÛ• ØªØ§ Ù‚ÙˆØªØ§Ø¨ÛŒØ§Ù† Ø¯Û•Ø³Øª Ø¨Ú©Û•Ù† Ø¨Û• Ø¨ÚµØ§ÙˆÚ©Ø±Ø¯Ù†Û•ÙˆÛ•ÛŒ Ù¾Ø±Ø³ÛŒØ§Ø±ØŒ ÙˆÛŽÙ†Û•ØŒ Ú¯Ø±ÙˆÙ¾ÛŒ Ø®ÙˆÛŽÙ†Ø¯Ù† Ùˆ Ù†ÙˆÛŽÚ©Ø§Ø±ÛŒÛŒÛ•Ú©Ø§Ù†ÛŒ Ø²Ø§Ù†Ú©Û†. Ø¦Ø§Ù…Ø§Ù†Ø¬ Ø¦Û•ÙˆÛ•ÛŒÛ• Ø¦Û•Ù¾Û•Ú©Û• Ø²ÛŒÙ†Ø¯ÙˆÙˆ Ø¨ÛŽØª Ø¨Û•Ø¨ÛŽ Ø¦Û•ÙˆÛ•ÛŒ ÙˆÛ•Ú© Ù‡Û•ÙˆØ§ÚµÛŒ ÙÛ•Ø±Ù…ÛŒ Ù¾ÛŒØ´Ø§Ù† Ø¨Ø¯Ø±ÛŽØª."}',
  'https://images.unsplash.com/photo-1523580846011-d3a5bc25702b?auto=format&fit=crop&q=80&w=900',
  'mixed',
  'pending_review',
  'seed-highlight-seed-social-campus-welcome-english',
  85,
  'This is a starter social post until students begin posting their real campus questions, photos, study groups, and daily university updates. The goal is to keep the app warm without pretending this is official news.',
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

INSERT OR IGNORE INTO highlight_items (
  id,
  category,
  title,
  organization,
  governorate,
  city,
  university_id,
  source_name,
  source_url,
  apply_url,
  event_date,
  deadline,
  summary,
  full_description_optional,
  image_url,
  language,
  status,
  duplicate_key,
  confidence_score,
  raw_text,
  created_at,
  updated_at
)
VALUES (
  'seed-social-study-group-demo',
  'student_club',
  'Looking for study partners this week?',
  'Jamiaati Campus Life',
  'all',
  'All Iraq',
  'all',
  'Jamiaati Campus Life',
  'internal-demo-study-group',
  'https://https-github-com-mahdialmuntadhar1-rgb-studenthub-plus.pages.dev',
  '',
  '',
  'A sample campus-life post encouraging students to create study groups, ask questions, and share helpful notes. This can be replaced by real user posts once the app grows.',
  '{"titleAR":"Ù‡Ù„ ØªØ¨Ø­Ø« Ø¹Ù† Ø²Ù…Ù„Ø§Ø¡ Ù„Ù„Ø¯Ø±Ø§Ø³Ø© Ù‡Ø°Ø§ Ø§Ù„Ø£Ø³Ø¨ÙˆØ¹ØŸ","titleKU":"Ø¦Û•Ù… Ù‡Û•ÙØªÛ•ÛŒÛ• Ù‡Ø§ÙˆÚ•ÛŽÛŒ Ø®ÙˆÛŽÙ†Ø¯Ù† Ø¯Û•Ú¯Û•Ú•ÛŽÛŒØªØŸ","contentAR":"Ù…Ù†Ø´ÙˆØ± ØªØ¬Ø±ÙŠØ¨ÙŠ Ù…Ù† Ø§Ù„Ø­ÙŠØ§Ø© Ø§Ù„Ø¬Ø§Ù…Ø¹ÙŠØ© ÙŠØ´Ø¬Ø¹ Ø§Ù„Ø·Ù„Ø§Ø¨ Ø¹Ù„Ù‰ Ø¥Ù†Ø´Ø§Ø¡ Ù…Ø¬Ù…ÙˆØ¹Ø§Øª Ø¯Ø±Ø§Ø³Ø© ÙˆØ·Ø±Ø­ Ø§Ù„Ø£Ø³Ø¦Ù„Ø© ÙˆÙ…Ø´Ø§Ø±ÙƒØ© Ø§Ù„Ù…Ù„Ø§Ø²Ù… Ø§Ù„Ù…ÙÙŠØ¯Ø©. ÙŠÙ…ÙƒÙ† Ø§Ø³ØªØ¨Ø¯Ø§Ù„Ù‡ Ø¨Ù…Ù†Ø´ÙˆØ±Ø§Øª Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…ÙŠÙ† Ù„Ø§Ø­Ù‚Ø§Ù‹.","contentKU":"Ù¾Û†Ø³ØªÛŽÚ©ÛŒ Ù†Ù…ÙˆÙˆÙ†Û•ÛŒÛŒÛ• Ø¨Û† Ú˜ÛŒØ§Ù†ÛŒ Ø²Ø§Ù†Ú©Û† Ú©Û• Ù‚ÙˆØªØ§Ø¨ÛŒØ§Ù† Ù‡Ø§Ù†Ø¯Û•Ø¯Ø§Øª Ú¯Ø±ÙˆÙ¾ÛŒ Ø®ÙˆÛŽÙ†Ø¯Ù† Ø¯Ø±ÙˆØ³Øª Ø¨Ú©Û•Ù†ØŒ Ù¾Ø±Ø³ÛŒØ§Ø± Ø¨Ú©Û•Ù† Ùˆ ØªÛŽØ¨ÛŒÙ†ÛŒÛŒÛ• Ø¨Û•Ø³ÙˆÙˆØ¯Û•Ú©Ø§Ù† Ù‡Ø§ÙˆØ¨Û•Ø´ Ø¨Ú©Û•Ù†. Ø¯ÙˆØ§ØªØ± Ø¯Û•ØªÙˆØ§Ù†Ø±ÛŽØª Ø¨Û• Ù¾Û†Ø³ØªÛŒ Ú•Ø§Ø³ØªÛ•Ù‚ÛŒÙ†Û•ÛŒ Ø¨Û•Ú©Ø§Ø±Ù‡ÛŽÙ†Û•Ø±Ø§Ù† Ø¨Ú¯Û†Ú•Ø¯Ø±ÛŽØª."}',
  'https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=900',
  'mixed',
  'pending_review',
  'seed-highlight-seed-social-study-group-demo',
  85,
  'A sample campus-life post encouraging students to create study groups, ask questions, and share helpful notes. This can be replaced by real user posts once the app grows.',
  '2026-06-14T11:18:10.105Z',
  '2026-06-14T11:18:10.105Z'
);

-- End seed file.

